#ifndef CONSOLE_COLORS_H
#define CONSOLE_COLORS_H

#include <Windows.h>

#define RED FOREGROUND_RED
#define GREEN FOREGROUND_GREEN
#define BLUE FOREGROUND_BLUE
#define SKYBLUE (FOREGROUND_INTENSITY | FOREGROUND_BLUE)
#define PINK (FOREGROUND_INTENSITY | FOREGROUND_RED)
#define LIME (FOREGROUND_INTENSITY | FOREGROUND_GREEN)
#define YELLOW (FOREGROUND_RED | FOREGROUND_GREEN)
#define WHITE (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)

#endif
